### ISSUE TITLE
cast: fix indentation issue

### ISSUE THREAD

**Issue by a1eaiactaest** [a1eaiactaest/gocomp#2]
Here: https://github.com/a1eaiactaest/gocomp/blob/3420e478bdaf50354219d31345c4ca38c61f7f1c/cast/cast.go#L13

**Comment by a1eaiactaest** [comment]
This problem appears to bo repo-wide. Fix all the files. There must have been some tab duplication during copy and paste.

**Comment by SasalBartosz** [comment]
Try running `go fmt` command in every folder containing .go files, that should format files accordingly to the default Golang standards.

**Comment by a1eaiactaest** [comment]
@NullBy1e it looked liked `go fmt` sets tab length to 8 spaces after running `git diff`, but still looked good in text editors. Pushed to the remote and it indeed looks good. Thanks. Fixed in 531412ba26dbb902744c33f52ca2b3570ee42f51
